imports = [
    'cgmath::Vector2',
    'content::DoorState',
]

[components]
coord = { type = 'Vector2<u32>' }
position = { type = 'Vector2<f32>' }
solid = {}
opacity = { type = 'f64' }
door_state = { type = 'DoorState' }
wall = {}
