imports = [
    'cgmath::Vector2',
    'content::DoorInfo',
    'content::TileSprite',
    'content::DepthInfo',
    'content::SpriteEffectInfo',
    'content::LightInfo',
    'content::HealthInfo',
    'content::FieldUiOffsets',
]

[components]
position = { type = 'Vector2<f32>', name = 'Position' }
coord = { type = 'Vector2<i32>', name = 'Coord' }
solid = { name = 'Solid' }
collider = { name = 'Collider' }
opacity = { type = 'f32', name = 'Opacity' }
door = { type = 'DoorInfo', name = 'Door', store = 'hash' }
door_closing_finished = { name = 'DoorClosingFinished', store = 'none' }
door_opener = { name = 'DoorOpener' }
wall = { name = 'Wall' }
player = { name = 'Player' }
sprite = { type = 'TileSprite', name = 'Sprite' }
depth = { type = 'DepthInfo', name = 'Depth' }
sprite_effect = { type = 'SpriteEffectInfo', name = 'SpriteEffect' }
light = { type = 'LightInfo', name = 'Light', store = 'btree' }
npc = { name = 'Npc', store = 'hash' }
bump_attack = { name = 'BumpAttack' }
attackable = { name = 'Attackable' }
health = { type = 'HealthInfo', name = 'Health' }
field_ui = { type = 'FieldUiOffsets', name = 'FieldUi', store = 'btree' }
hide_in_dark = { name = 'HideInDark' }
