imports = [
    'cgmath::Vector2',
    'content::DoorState',
    'content::Sprite',
]

[components]
position = { type = 'Vector2<f32>' }
solid = {}
opacity = { type = 'f64' }
door_state = { type = 'DoorState' }
wall = {}
player = {}
sprite = { type = 'Sprite' }
depth = { type = 'f32' }
