imports = [
    'cgmath::Vector2',
    'content::DoorInfo',
    'content::Sprite',
    'content::DepthInfo',
    'content::SpriteEffectInfo',
]

[components]
position = { type = 'Vector2<f32>', name = 'Position' }
solid = { name = 'Solid' }
collider = { name = 'Collider' }
opacity = { type = 'f64', name = 'Opacity' }
door = { type = 'DoorInfo', name = 'Door', store = 'hash' }
door_closing_finished = { name = 'DoorClosingFinished', store = 'none' }
door_opener = { name = 'DoorOpener' }
wall = { name = 'Wall' }
player = { name = 'Player' }
sprite = { type = 'Sprite', name = 'Sprite' }
depth = { type = 'DepthInfo', name = 'Depth' }
sprite_effect = { type = 'SpriteEffectInfo', name = 'SpriteEffect' }
