imports = [
    'cgmath::Vector2',
]

position_component = 'position'

[fields]
opacity_total = { component = 'opacity', aggregate = 'f32_total' }
solid_count = { component = 'solid', aggregate = 'count' }
door_set = { component = 'door', aggregate = 'set' }
wall_neighbours = { component = 'wall', aggregate = 'neighbour_count' }
wall_set = { component = 'wall', aggregate = 'set' }
enemy_set = { component = 'enemy', aggregate = 'set' }
